### ISSUE TITLE
How to use this pluging ? 

### ISSUE THREAD

**Issue by hugobqd** [paulmassen/grav-plugin-image64#1]
Bonjour,
Je suis très intéressé par cette fonctionnalité. Est-ce que ce plugin fonctionne ? Il n'est pas affiché sur la page des plugins Grav et la section 'Usage' is empty. D'avance merci. Hugo

**Comment by paulmassen** [comment]
Bonjour Hugo, 

Malheureusement je n'ai jamais publié ce plugin, car il n'est pas terminé.
Il existe un filtre twig |base64_encode mais je ne crois pas qu'il puisse convertir des images.

Je tacherai de le finir un jour et te le signalerai ici.

Paul

**Comment by hugobqd** [comment]
C'est noté, merci pour la réponse Paul !
